Feat(.local/bin/seal): Passphrase in dynamic menu
When not in a tty, prompt passphrase in dynamic menu to decrypt a file.

diff --git a/.local/bin/seal b/.local/bin/seal
--- a/.local/bin/seal
+++ b/.local/bin/seal
@@ -87,9 +87,19 @@ encrypt() {
 }
 
 decrypt() {
-    gpg -d "$file" \
-        && notify "Decryption finished" \
-        || abort "Decryption failed"
+    local pass=""
+
+    if [ "$XDG_SESSION_TYPE" = "tty" ]; then
+        read -p "$prompt decryption passphrase: " -r pass
+    else
+        menu="${HOME}/.local/bin/wmenu-color -P -p"
+        pass="$($menu "$prompt decyrption passphrase: " < /dev/null)"
+    fi
+    echo "$pass" | gpg --no-symkey-cache \
+                       --batch \
+                       --passphrase-fd 0 \
+                       -d "$file" \
+                 && notify "Decryption finished" || abort "Decryption failed"
 }
 
 sign() {
