update

diff --git a/.local/bin/sync-config b/.local/bin/sync-config
--- a/.local/bin/sync-config
+++ b/.local/bin/sync-config
@@ -1,27 +1,26 @@
-#!/bin/bash
-# sync-config
+#!/usr/bin/sh
 # @author nate zhou
-# @since 2024
+# @since 2024,2025
 
-heart="$HOME/doc/heart"
-dotfiles="$HOME/doc/unixchad/dotfiles"
+HEART="$HOME/doc/heart"
+DOTFILES="$HOME/doc/unixchad/dotfiles"
 
 read -p "Continue? (y/n): " choice
-if [[ $choice == "y" || $choice == "Y" ]]; then
-    pacman -Qmq | sort > "$heart"/aur.list
-    pacman -Qenq | sort > "$heart"/arch.list
+if [ $choice = "y" ] || [ $choice = "Y" ]; then
+    pacman -Qmq | sort > "$HEART"/aur.list
+    pacman -Qenq | sort > "$HEART"/arch.list
 
-    crontab -l > "$heart"/.config/crontab.backup && echo "crontab backup done" || echo "crontab backup failed"
+    crontab -l > "$HEART"/.config/crontab.backup && echo "crontab backup done" || echo "crontab backup failed"
 
     # censor bookmarks for screen casting
     grep -n "##############################below-are-private##############################" $HOME/doc/heart/.local/share/bookmarks/bookmarks | cut -d: -f1 | xargs -I {} sed -n '1,{}p' $HOME/doc/heart/.local/share/bookmarks/bookmarks > $HOME/doc/heart/.local/share/bookmarks/bookmarks-record && echo "bookmarks-record updated" || echo "bookmarks-record update failed"
 
     # unixchad
     if [ ! -d "$HOME/doc/.heart" ]; then
-        git clone "$heart" "$HOME/doc/.heart"
+        git clone "$HEART" "$HOME/doc/.heart"
     fi
     git --git-dir $HOME/doc/.heart/.git --work-tree $HOME/doc/.heart pull && echo "heart is pulled" || echo "heart pulling failed"
-    rsync -a --delete --exclude ".git" --exclude ".local/sbin" --exclude "arch.list" --exclude "aur.list" "$HOME/doc/.heart/" "$dotfiles" && chmod 755 "$dotfiles"
+    rsync -a --delete --exclude ".git" --exclude ".local/sbin" --exclude "arch.list" --exclude "aur.list" "$HOME/doc/.heart/" "$DOTFILES" && chmod 755 "$DOTFILES"
 else
     echo "aborted"
     exit 0
diff --git a/.local/bin/sync-config-cron b/.local/bin/sync-config-cron
--- a/.local/bin/sync-config-cron
+++ b/.local/bin/sync-config-cron
@@ -1,40 +1,39 @@
-#!/bin/bash
-# sync-config
+#!/usr/bin/env bash
 # @author nate zhou
-# @since 2024
+# @since 2024,2025
 
-heart="$HOME/doc/heart"
-dotfiles="$HOME/doc/unixchad/dotfiles"
-crontab="$HOME/.config/crontab.backup"
+HEART="$HOME/doc/heart"
+DOTFILES="$HOME/doc/unixchad/dotfiles"
+CRONTAB="$HOME/.config/crontab.backup"
 
 # modified time in seconds since the Epoch
-update_time=$(stat -c "%Y" "$crontab")
+update_time=$(stat -c "%Y" "$CRONTAB")
 # seconds since the Epoch
 current_time=$(date +%s)
 #update_frequency=86400 # in seconds, 86400s = 1d
-update_frequency=43200 # in seconds, 43200s = 12H
+UPDATE_FREQUENCY=43200 # in seconds, 43200s = 12H
 
 sync_config() {
     git --git-dir ~/doc/.heart/.git --work-tree ~/doc/.heart pull && echo "heart is pulled" || echo "heart pulling failed"
 
-    crontab -l > "$crontab" && echo "crontab backup done" || echo "crontab backup failed"
+    crontab -l > "$CRONTAB" && echo "crontab backup done" || echo "crontab backup failed"
 
     # censor bookmarks for screen casting
     grep -n "##############################below-are-private##############################" ~/doc/heart/.local/share/bookmarks/bookmarks | cut -d: -f1 | xargs -I {} sed -n '1,{}p' ~/doc/heart/.local/share/bookmarks/bookmarks > ~/doc/heart/.local/share/bookmarks/bookmarks-record && echo "bookmarks-record updated" || echo "bookmarks-record update failed"
 
     # unixchad
-    rsync -a --delete "$heart"/../.heart/ --exclude .git "$dotfiles" && chmod 755 "$dotfiles"
+    rsync -a --delete "$HEART"/../.heart/ --exclude .git "$DOTFILES" && chmod 755 "$DOTFILES"
 
 }
 
-if [[ ! -f "$crontab" ]]; then
+if [ ! -f "$CRONTAB" ]; then
     sync_config
     exit 0
 fi
 
-if [[ $(("$current_time" - "$update_time")) -gt "$update_frequency" ]]; then
+if ((current_time - update_time > UPDATE_FREQUENCY )); then
     sync_config
 else
-    echo "Already updated within past $(($update_frequency/3600)) hours"
+    echo "Already updated within past $(($UPDATE_FREQUENCY/3600)) hours"
     exit 1
 fi
diff --git a/.local/bin/wcast b/.local/bin/wcast
--- a/.local/bin/wcast
+++ b/.local/bin/wcast
@@ -1,16 +1,33 @@
-#!/bin/bash
-# @author nate zhou @since 2024
+#!/usr/bin/sh
+# @author nate zhou
+# @since 2024,2025
 # record-output record the selected output on wayland -a audio, -g geometry; -ro requires selecting one of the predefined rectangles for all outputs
-selected_output=$(swaymsg -t get_outputs -p | grep Output | wmenu -p "wshot: " -l 3 -f "SourceCodePro medium 13" -S 6f3f89 -s ffffff -M 6f3f89 -m ffffff | awk '{print $2}' )
+# also create an indicator for i3stauts
 
-wcast_state=$HOME/.cache/wcast
+#set -x
+selected_output="$(swaymsg -t get_outputs -p | grep Output | wmenu -p "wshot: " -l 3 -f "SourceCodePro medium 13" -S 6f3f89 -s ffffff -M 6f3f89 -m ffffff | awk '{print $2}' )"
+
+TMP_DIR="/tmp/i3status"
+
+[ -d "$TMP_DIR" ] || mkdir "$TMP_DIR"
+[ -d "$HOME/tmp" ] || mkdir "$HOME/tmp"
+
+WCAST_STATE="$TMP_DIR/wcast"
+
 cleanup() {
-    rm "$wcast_state"
-    killall -SIGUSR1 i3status
+    rm -f "$WCAST_STATE"
+    pgrep i3status >/dev/null && killall -SIGUSR1 i3status
 }
-echo REC > "$wcast_state"
-killall -SIGUSR1 i3status
-#wf-recorder --no-damage -r 30 --audio=rnnoise_source -g "$(slurp -ro)" -f ~/recording.mp4
-wf-recorder -r 30 --audio=rnnoise_source -o $selected_output -f ~/tmp/recording-$(date +%Y-%m-%d-%H-%M).mp4 || cleanup
 
-trap cleanup EXIT
+# Set the trap to call cleanup on SIGINT
+trap cleanup SIGINT
+
+# @TODO fix C-c signal in wf-recording
+# echo REC > "$WCAST_STATE"
+# killall -SIGUSR1 i3status
+
+# Start the recorder
+wf-recorder -r 30 --audio=rnnoise_source -o "$selected_output" -f "$HOME/tmp/recording-$(date +%Y-%m-%d-%H-%M).mp4"
+
+# Call cleanup explicitly in case of normal exit
+cleanup
